name: Check Domains

on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write # Allow pushing changes

jobs:
  check-domains:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run Domain Checker
      run: python check_domains.py
      
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
        
    - name: Commit and Push
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --global user.name 'Domain Bot'
        git config --global user.email 'bot@domain-checker.com'
        git add domains.json
        git commit -m "Update working domains [skip ci]"
        git push
